brainfuck: Abstract Syntax Tree
Abstract Syntax Tree
The abstract syntax tree that should be utilized by a proper implementation.
Data Structures
struct BrainfuckInstruction
This structure represents a single operation that could be executed.
union BrainfuckInstruction::BrainfuckArgument
The argument of this instruction, whose type depends on the operation of the instruction.
struct BrainfuckScript
A BrainfuckScript is a collection of BrainfuckInstruction structures.
Enumerations
enum BrainfuckInstruction::BrainfuckType {
BrainfuckInstruction::INC, BrainfuckInstruction::DEC, BrainfuckInstruction::MOVL, BrainfuckInstruction::MOVR,
BrainfuckInstruction::CLR, BrainfuckInstruction::IN, BrainfuckInstruction::OUT, BrainfuckInstruction::JMP,
BrainfuckInstruction::JZ, BrainfuckInstruction::NOP
}
This enum defines the instruction set that should be implemented by a proper implementation of this specification.
Functions
struct BrainfuckInstruction * brainfuck_instruction_alloc (void)
Allocate a BrainfuckInstruction structure.
void brainfuck_instruction_dealloc (struct BrainfuckInstruction *instruction)
Deallocate the given instruction.
struct BrainfuckScript * brainfuck_script_alloc (void)
Allocate a BrainfuckScript structure.
void brainfuck_script_dealloc (struct BrainfuckScript *script)
Deallocate the given script including the structures referenced by the next field.
int brainfuck_script_init (struct BrainfuckScript *script, struct BrainfuckScript *previous, size_t size)
Initialize a BrainfuckScript structure.
void brainfuck_script_dump (const struct BrainfuckScript *script, FILE *file)
Dump the AST of the given BrainfuckScript structure.
Detailed Description
The abstract syntax tree that should be utilized by a proper implementation.
Enumeration Type Documentation
enum BrainfuckInstruction::BrainfuckType
This enum defines the instruction set that should be implemented by a proper implementation of this specification.
Enumerator
INC
Increase cell value.
DEC
Decrease cell value.
MOVL
Move left in the memory.
MOVR
Move right in the memory.
CLR
Clear cell value.
IN
Read one byte from a stream and write to cell.
OUT
Read one byte from cell and write to a stream.
JMP
Unconditional jump.
JZ
Conditional jump: if zero.
NOP
No operation.
Definition at line 65 of file brainfuck.h.
Function Documentation
struct BrainfuckInstruction* brainfuck_instruction_alloc (void)
Allocate a BrainfuckInstruction structure.
Returns
A pointer to the allocated structure or NULL if the allocation failed.
Definition at line 42 of file brainfuck.c.
void brainfuck_instruction_dealloc (struct BrainfuckInstruction * instruction)
Deallocate the given instruction.
Parameters
instruction The instruction to deallocate.
Definition at line 47 of file brainfuck.c.
struct BrainfuckScript* brainfuck_script_alloc (void)
Allocate a BrainfuckScript structure.
Returns
A pointer to the allocated structure or NULL if the allocation failed.
Definition at line 52 of file brainfuck.c.
Referenced by brainfuck_parser_parse_string_partial().
void brainfuck_script_dealloc (struct BrainfuckScript * script)
Deallocate the given script including the structures referenced by the next field.
Parameters
script The script to deallocate.
Definition at line 58 of file brainfuck.c.
References BrainfuckScript::array, and BrainfuckScript::next.
Referenced by brainfuck_parser_parse_file(), and brainfuck_parser_parse_string().
void brainfuck_script_dump (const struct BrainfuckScript * script, FILE * file)
Dump the AST of the given BrainfuckScript structure.
Parameters
script The script to dump.
file A pointer to a FILE object to write the script to.
Definition at line 81 of file brainfuck.c.
References BrainfuckScript::array, BrainfuckInstruction::CLR, BrainfuckInstruction::DEC, BrainfuckInstruction::IN, BrainfuckInstruction::INC, BrainfuckScript::index, BrainfuckInstruction::JMP, BrainfuckInstruction::JZ, BrainfuckInstruction::MOVL, BrainfuckInstruction::MOVR, BrainfuckInstruction::BrainfuckArgument::n, BrainfuckScript::next, BrainfuckInstruction::NOP, BrainfuckInstruction::BrainfuckArgument::offset, and BrainfuckInstruction::OUT.
int brainfuck_script_init (struct BrainfuckScript * script, struct BrainfuckScript * previous, size_t size)
Initialize a BrainfuckScript structure.
Parameters
script The BrainfuckScript structure to initialize.
previous The previous BrainfuckScript structure.
size The size of the array to allocate.
Returns
BRAINFUCK_EOK on success, one of the defined error codes on failure.
Definition at line 68 of file brainfuck.c.
References BrainfuckScript::array, BRAINFUCK_ENOMEM, BRAINFUCK_EOK, BrainfuckScript::index, BrainfuckScript::previous, and BrainfuckScript::size.
Referenced by brainfuck_parser_parse_string_partial().