brainfuck: Parser
Parser
A parser interface for the brainfuck language.
Data Structures
struct BrainfuckParserContext
This structure contains the state of the parser.
struct BrainfuckParserContext::BrainfuckOffsetStack
A stack containing the jump offsets.
Functions
struct BrainfuckParserContext * brainfuck_parser_context_alloc (void)
Allocate a BrainfuckParserContext structure.
void brainfuck_parser_context_dealloc (struct BrainfuckParserContext *ctx)
Deallocate the given BrainfuckParserContext structure.
int brainfuck_parser_context_init (struct BrainfuckParserContext *ctx)
Initialize a BrainfuckParserContext structure.
int brainfuck_parser_validate (const struct BrainfuckParserContext *ctx)
Validate a script and detect syntax errors in the given script.
void brainfuck_parser_parse_string_partial (const char *string, struct BrainfuckParserContext *ctx, int *error)
Parse the given string as a segment of a script.
struct BrainfuckScript * brainfuck_parser_parse_string (const char *string, int *error)
Parse the given string.
struct BrainfuckScript * brainfuck_parser_parse_file (FILE *file, int *error)
Parse the given file.
Detailed Description
A parser interface for the brainfuck language.
Function Documentation
struct BrainfuckParserContext* brainfuck_parser_context_alloc (void)
Allocate a BrainfuckParserContext structure.
Returns
A pointer to allocated structure or NULL if the allocation failed.
Definition at line 130 of file brainfuck.c.
void brainfuck_parser_context_dealloc (struct BrainfuckParserContext * ctx)
Deallocate the given BrainfuckParserContext structure.
Parameters
ctx The context to deallocate.
Definition at line 135 of file brainfuck.c.
References BrainfuckParserContext::BrainfuckOffsetStack::array.
int brainfuck_parser_context_init (struct BrainfuckParserContext * ctx)
Initialize a BrainfuckParserContext structure.
Parameters
ctx The BrainfuckParserContext structure to initialize.
Returns
BRAINFUCK_EOK on success, one of the defined error codes on failure.
Definition at line 142 of file brainfuck.c.
References BrainfuckParserContext::BrainfuckOffsetStack::array, BRAINFUCK_ENOMEM, BRAINFUCK_EOK, BrainfuckParserContext::BrainfuckOffsetStack::index, and BrainfuckParserContext::BrainfuckOffsetStack::size.
Referenced by brainfuck_parser_parse_string_partial().
struct BrainfuckScript* brainfuck_parser_parse_file (FILE * file, int * error)
Parse the given file.
Parameters
file The file to parse.
error A pointer to an integer that will be set to either a success or an error code.
Returns
A pointer to a BrainfuckScript instance or NULL if the parsing failed.
Definition at line 318 of file brainfuck.c.
References BrainfuckParserContext::BrainfuckOffsetStack::array, BRAINFUCK_EOK, BRAINFUCK_ESYNTAX, brainfuck_parser_parse_string_partial(), brainfuck_parser_validate(), brainfuck_script_dealloc(), and BrainfuckParserContext::head.
struct BrainfuckScript* brainfuck_parser_parse_string (const char * string, int * error)
Parse the given string.
Parameters
string The string to parse.
error A pointer to an integer that will be set to either a success code or an error code.
Returns
A pointer to a BrainfuckScript instance or NULL if the parsing failed.
Definition at line 290 of file brainfuck.c.
References BrainfuckParserContext::BrainfuckOffsetStack::array, BRAINFUCK_EOK, BRAINFUCK_ESYNTAX, brainfuck_parser_parse_string_partial(), brainfuck_parser_validate(), brainfuck_script_dealloc(), and BrainfuckParserContext::head.
void brainfuck_parser_parse_string_partial (const char * string, struct BrainfuckParserContext * ctx, int * error)
Parse the given string as a segment of a script.
It is not gauranteed that all syntax errors will be detected, since the parser can only partially parse the script and therefore cannot detect syntax errors like unclosed brackets. Use brainfuck_parser_validate to validate a script after parsing.
Parameters
string The string to parse.
ctx The context of the parser.
error A pointer to an integer that will be set to either a success code or an error code.
Definition at line 162 of file brainfuck.c.
References BrainfuckScript::array, BrainfuckParserContext::BrainfuckOffsetStack::array, BRAINFUCK_ENOMEM, BRAINFUCK_EOK, BRAINFUCK_ESYNTAX, brainfuck_parser_context_init(), brainfuck_script_alloc(), brainfuck_script_init(), BrainfuckParserContext::BrainfuckOffsetStack::current, BrainfuckInstruction::DEC, BrainfuckParserContext::head, BrainfuckInstruction::IN, BrainfuckInstruction::INC, BrainfuckScript::index, BrainfuckParserContext::BrainfuckOffsetStack::index, BrainfuckInstruction::JMP, BrainfuckInstruction::JZ, BrainfuckInstruction::MOVL, BrainfuckInstruction::MOVR, BrainfuckInstruction::BrainfuckArgument::n, BrainfuckScript::next, BrainfuckInstruction::BrainfuckArgument::offset, BrainfuckInstruction::OUT, BrainfuckScript::size, BrainfuckParserContext::BrainfuckOffsetStack::size, and BrainfuckParserContext::tail.
Referenced by brainfuck_parser_parse_file(), and brainfuck_parser_parse_string().
int brainfuck_parser_validate (const struct BrainfuckParserContext * ctx)
Validate a script and detect syntax errors in the given script.
Parameters
ctx The context of the parser.
Returns
true if the given script does not contain syntax errors, false otherwise.
Definition at line 156 of file brainfuck.c.
References BrainfuckParserContext::BrainfuckOffsetStack::index.
Referenced by brainfuck_parser_parse_file(), and brainfuck_parser_parse_string().